name: CallerWorkflow

on:
  workflow_dispatch:
  
jobs:
  call_reusableWorkflow:
    uses: ./.github/workflows/ReusableWorkflow1.yml
    with:
      EnableRunner1: true
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Checkout code
        uses: actions/checkout@v2
  
  
      
     

